# Generated by Django 4.2.1 on 2023-07-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(max_length=128, null=True)),
                ('lastTimeInteracted', models.IntegerField(null=True)),
                ('img', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeToSendNext', models.IntegerField()),
                ('text', models.TextField()),
                ('bitrixId', models.IntegerField()),
                ('typeId', models.IntegerField(default=1)),
                ('notificatedCount', models.IntegerField(default=0)),
                ('sendInterval', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('section', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tgid', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('isManager', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.department')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tgid', models.IntegerField(null=True)),
                ('from_user', models.CharField(max_length=64)),
                ('departmentName', models.CharField(max_length=64, null=True)),
                ('text', models.TextField(null=True)),
                ('typeOfMessage', models.CharField(choices=[('photo', 'photo'), ('text', 'text'), ('audio', 'audio'), ('video', 'video'), ('document', 'document'), ('tag', 'tag')], default='text', max_length=25)),
                ('time', models.CharField(max_length=100)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
                ('responsiblePerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.users')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to='chats.users'),
        ),
        migrations.CreateModel(
            name='UnrecievedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrecieved', models.IntegerField(default=0)),
                ('taged', models.BooleanField(default=False)),
                ('folder', models.CharField(max_length=100, null=True)),
                ('chat', models.ForeignKey(default=942368094, on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.users')),
            ],
            options={
                'unique_together': {('user', 'chat')},
            },
        ),
    ]
