# Generated by Django 4.2.4 on 2023-08-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_notification_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
    ]
