# Generated by Django 4.2.4 on 2023-08-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_notification_dateforrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='botName',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
