# Generated by Django 4.2.4 on 2023-08-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_department_botname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(db_collation='utf8mb4_bin', null=True),
        ),
    ]
