# Generated by Django 4.2.4 on 2023-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tgMembers',
            field=models.TextField(null=True),
        ),
    ]
