# Generated by Django 4.2.4 on 2023-08-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chat_tgmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tgMembers',
            field=models.JSONField(null=True),
        ),
    ]
