# Generated by Django 4.2.4 on 2023-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_chat_tgmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='previousId',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
